---
ovn_sdn_migration_timeout: 180
checks:
  - "oc wait co --all --for='condition=Available=True' --timeout=60s"
  - "oc wait co --all --for='condition=Progressing=False' --timeout=60s"
  - "oc wait co --all --for='condition=Degraded=False' --timeout=60s"
# Default expected network type
expected_network_type: OVNKubernetes
network_provider_config: openshiftSDNConfig
namespace: openshift-sdn

