- name: End-to-End Tests for `check_network_policy_mode` module
  hosts: localhost
  gather_facts: no
  vars:
    network_policy_mode: "NetworkPolicy"  # Expected mode
    timeout_value: 60  # Lower timeout for testing

  tasks:
    - name: Run `check_network_policy_mode` module
      check_network_policy_mode:
        timeout: "{{ timeout_value }}"
      register: network_policy_result
      ignore_errors: yes  # Allow the playbook to continue even if it fails

    - name: Debug output of `check_network_policy_mode`
      debug:
        var: network_policy_result

    - name: Assert success when NetworkPolicy is set
      assert:
        that:
          - "'The cluster is correctly configured with NetworkPolicy isolation mode.' in network_policy_result.msg"
        fail_msg: "Cluster should be using NetworkPolicy, but it is not!"
      when: "'The cluster is correctly configured with NetworkPolicy isolation mode' in network_policy_result.msg"

    - name: Assert failure when NetworkPolicy is not set
      assert:
        that:
          - "'The cluster is not configured with NetworkPolicy isolation mode' in network_policy_result.msg"
        fail_msg: "Module did not detect missing NetworkPolicy mode!"
      when: network_policy_result.failed

    - name: Test unknown mode handling
      assert:
        that:
          - "'Could not determine the isolation mode' in network_policy_result.msg"
        fail_msg: "Module did not handle unknown mode properly!"
      when: "'unknown' in network_policy_result.msg"

    - name: Test timeout behavior
      assert:
        that:
          - "'Timeout waiting for network policy data' in network_policy_result.msg"
        fail_msg: "Timeout handling did not work as expected!"
      when: network_policy_result.failed and 'Timeout' in network_policy_result.msg

    - name: Fail if the module fails unexpectedly
      fail:
        msg: "Module failed unexpectedly: {{ network_policy_result.msg }}"
      when: network_policy_result.failed and "The cluster is not configured with NetworkPolicy isolation mode" not in network_policy_result.msg
