---
- name: Check all cluster operators back to normal
  verify_cluster_operators_health:
    max_timeout: "{{ ovn_sdn_migration_timeout | default(2700) }}"
    pause_between_checks: 30
    required_success_count: 3
  register: result

- name: Display the cluster operators status
  shell: oc get co
  when: result.changed

